### ISSUE TITLE
Climpact doesn't fail when dates are missing in input file

### ISSUE THREAD

**Issue by heroldn** [ARCCSS-extremes/climpact#1]
e.g. in the following snippet the 29th day of the month is missing. Climpact should fail or throw a warning.
1950	5	27	0	20	8.3
1950	5	28	0	19.6	9.8
1950	5	30	0	22.1	8.3
1950	5	31	0	20.1	8.3

**Comment by lisavalexander** [comment]
A warning would be better

**Comment by heroldn** [comment]
I'm quite sure it already fails with a warning(?).
