### ISSUE TITLE
No linear trends: Requires at least 10 data points and 70% of time-series to be valid

### ISSUE THREAD

**Issue by beatrizjusten** [ARCCSS-extremes/climpact#102]
This error appears only for the precipitation indices. My database goes from 1961 to 2021.
![ERROR](https://github.com/ARCCSS-extremes/climpact/assets/135774715/921c0a99-c865-484e-bd71-55c4b792d1fd)

**Comment by heroldn** [comment]
The message indicates you need 70% of the data to be present.
