### ISSUE TITLE
Error in library(qpdf) : there is no package called ‘qpdf’

### ISSUE THREAD

**Issue by GerardoTheMeteorologist** [ARCCSS-extremes/climpact#103]
Hi there! 
I'm a student from the Universidad Veracruzana and I'm gonna be doing a thesis about climate change index, so in order to complete it, I'll be using Climpact. I have already installed climpact in Windows, and I didn't have any problem opening Climpact using
Library(shiny)
runApp()
It worked perfectly but I wanted to install it in linux too, since my advisory told me that in linux would be better for all the work we will be doing. When I installed Climpact using R it gave me 8 errors from packages:
Warning messages:
1: In install.packages(packages[package]) :
  installation of package ‘ncdf4’ had non-zero exit status
2: In install.packages(packages[package]) :
  installation of package ‘udunits2’ had non-zero exit status
3: In install.packages(packages[package]) :
  installation of package ‘proj4’ had non-zero exit status
4: In install.packages(packages[package]) :
  installation of package ‘curl’ had non-zero exit status
5: In install.packages(packages[package]) :
  installation of package ‘qpdf’ had non-zero exit status
6: In install.packages("./server/pcic_packages/ncdf4.helpers_0.3-3.tar.gz",  :
  installation of package ‘./server/pcic_packages/ncdf4.helpers_0.3-3.tar.gz’ had non-zero exit status
7: In install.packages("./server/pcic_packages/ncdf4.helpers_0.3-3.tar.gz",  :
  installation of package ‘./server/pcic_packages/ncdf4.helpers_0.3-3.tar.gz’ had non-zero exit status
8: In install.packages("./server/pcic_packages/climdex.pcic.ncdf.climpact.tar.gz",  :
  installation of package ‘./server/pcic_packages/climdex.pcic.ncdf.climpact.tar.gz’ had non-zero exit status
  And when I wanted to open Climpact with library(shiny) runApp() it gave me this error so I couldn't open it:
  Error in library(qpdf) : there is no package called ‘qpdf’
  Any clues about what would be going on? I will really appreciate if someone could help me out with this. Please.

**Comment by heroldn** [comment]
Hi Gerardo
 
Did you install the system packages related to PROJ4 and udunits in your linux system before trying to install? And is that all the output that the terminal gave you?
 
Cheers
 
Nick.

**Comment by GerardoTheMeteorologist** [comment]
@heroldn Hi Nick, thanks for your response.
I think that would be the problem, I will be installing the system packages related to PROJ4 and udnits in my linux system and I'll keep this issue updated if that doesn't work.
Thank you very much.
Gerardo.

**Comment by GerardoTheMeteorologist** [comment]
Hi there again, @heroldn , hope you are doing well.
I did install proj4 and udnits in my linux system but I'm still not able to start climpact from R. I don't know what I'm doing wrong, I installed proj4 using:
sudo apt-get install proj-bin
[sudo] password for gerardo: 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed
  proj-bin
0 to upgrade, 1 to newly install, 0 to remove and 126 not to upgrade.
Need to get 154 kB of archives.
After this operation, 492 kB of additional disk space will be used.
Get:1 http://mx.archive.ubuntu.com/ubuntu jammy/universe amd64 proj-bin amd64 8.2.1-1 [154 kB]
Fetched 154 kB in 1s (149 kB/s)   
Selecting previously unselected package proj-bin.
(Reading database ... 302320 files and directories currently installed.)
Preparing to unpack .../proj-bin_8.2.1-1_amd64.deb ...
Unpacking proj-bin (8.2.1-1) ...
Setting up proj-bin (8.2.1-1) ...
Processing triggers for man-db (2.10.2-1) ...
and also I installed udnits using:
sudo apt-get update
sudo apt-get install udunits-bin
Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Hit:2 http://mx.archive.ubuntu.com/ubuntu jammy InRelease 
Get:3 http://mx.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:4 http://mx.archive.ubuntu.com/ubuntu jammy-backports InRelease [108 kB]
Get:5 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [631 kB]
Get:6 http://mx.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [850 kB]
Get:7 http://security.ubuntu.com/ubuntu jammy-security/main i386 Packages [277 kB]
Get:8 http://security.ubuntu.com/ubuntu jammy-security/main Translation-en [148 kB]
Get:9 http://security.ubuntu.com/ubuntu jammy-security/main amd64 DEP-11 Metadata [41.6 kB]
Get:10 http://security.ubuntu.com/ubuntu jammy-security/main amd64 c-n-f Metadata [11.0 kB]
Get:11 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [651 kB]
Get:12 http://security.ubuntu.com/ubuntu jammy-security/restricted Translation-en [104 kB]
Get:13 http://security.ubuntu.com/ubuntu jammy-security/universe i386 Packages [542 kB]
Get:14 http://mx.archive.ubuntu.com/ubuntu jammy-updates/main i386 Packages [453 kB]
Get:15 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [754 kB]
Get:16 http://security.ubuntu.com/ubuntu jammy-security/universe Translation-en [135 kB]
Get:17 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 DEP-11 Metadata [22.0 kB]
Get:18 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 c-n-f Metadata [15.8 kB]
Get:19 http://mx.archive.ubuntu.com/ubuntu jammy-updates/main Translation-en [208 kB]
Get:20 http://mx.archive.ubuntu.com/ubuntu jammy-updates/main amd64 DEP-11 Metadata [99.4 kB]
Get:21 http://mx.archive.ubuntu.com/ubuntu jammy-updates/main amd64 c-n-f Metadata [15.4 kB]
Get:22 http://mx.archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [663 kB]
Get:23 http://mx.archive.ubuntu.com/ubuntu jammy-updates/restricted Translation-en [106 kB]
Get:24 http://mx.archive.ubuntu.com/ubuntu jammy-updates/universe i386 Packages [636 kB]
Get:25 http://mx.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [949 kB]
Get:26 http://mx.archive.ubuntu.com/ubuntu jammy-updates/universe Translation-en [204 kB]
Get:27 http://mx.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 DEP-11 Metadata [274 kB]
Get:28 http://mx.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 c-n-f Metadata [20.8 kB]
Get:29 http://mx.archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 DEP-11 Metadata [940 B]
Get:30 http://mx.archive.ubuntu.com/ubuntu jammy-backports/main amd64 DEP-11 Metadata [7 968 B]
Get:31 http://mx.archive.ubuntu.com/ubuntu jammy-backports/universe amd64 DEP-11 Metadata [15.4 kB]
Fetched 8 173 kB in 14s (598 kB/s)                                             
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed
  udunits-bin
0 to upgrade, 1 to newly install, 0 to remove and 131 not to upgrade.
Need to get 130 kB of archives.
After this operation, 184 kB of additional disk space will be used.
Get:1 http://mx.archive.ubuntu.com/ubuntu jammy/universe amd64 udunits-bin amd64 2.2.28-3 [130 kB]
Fetched 130 kB in 1s (144 kB/s)      
Selecting previously unselected package udunits-bin.
(Reading database ... 302345 files and directories currently installed.)
Preparing to unpack .../udunits-bin_2.2.28-3_amd64.deb ...
Unpacking udunits-bin (2.2.28-3) ...
Setting up udunits-bin (2.2.28-3) ...
Processing triggers for install-info (6.8-4build1) ...
and then I tried to open Climpact: 
gerardo@Tesis:~/Downloads/climpact-master$ R

R version 4.1.2 (2021-11-01) -- "Bird Hippie"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(shiny) 
runApp()

Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

Loading required package: Kendall
Loading required package: tcltk

Attaching package: ‘tcltk2’

The following object is masked from ‘package:shiny’:

    tag

Use suppressPackageStartupMessages() to eliminate package startup messages.

Attaching package: ‘shinyjs’

The following object is masked from ‘package:tcltk2’:

    disabled

The following object is masked from ‘package:shiny’:

    runExample

The following objects are masked from ‘package:methods’:

    removeClass, show


Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

corrplot 0.92 loaded

Attaching package: ‘shinydashboard’

The following object is masked from ‘package:graphics’:

    box


Attaching package: ‘shinyWidgets’

The following object is masked from ‘package:shinyjs’:

    alert

Error in library(qpdf) : there is no package called ‘qpdf’
> 
But I'm still having the same problem. What could I do now? Or how can I install Proj4 and udnits in my linux system? Thanks a lot for the help, and have a nice day!
Cheers
Gerardo.

**Comment by heroldn** [comment]
Hi Gerardo
 
The README mentions the libproj-dev and libudunits2-dev packages. Did you try those?
 
Nick.

**Comment by GerardoTheMeteorologist** [comment]
Hi @heroldn , I really appreciate your help. 
I have already installed the libproj-dev and the libudnits2-dev packages, but sadly I'm still having the same error when I try to open Climpact from R:
gerardo@Tesis:~/Downloads/climpact-master$ sudo apt-get install -y libproj-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libdeflate-dev libjbig-dev libsqlite3-dev libtiff-dev libtiffxx5
Suggested packages:
  sqlite3-doc
The following NEW packages will be installed
  libdeflate-dev libjbig-dev libproj-dev libsqlite3-dev libtiff-dev libtiffxx5
0 to upgrade, 6 to newly install, 0 to remove and 131 not to upgrade.
Need to get 2 846 kB of archives.
After this operation, 14.7 MB of additional disk space will be used.
Get:1 http://mx.archive.ubuntu.com/ubuntu jammy/main amd64 libdeflate-dev amd64 1.10-2 [59.2 kB]
Get:2 http://mx.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libsqlite3-dev amd64 3.37.2-2ubuntu0.1 [846 kB]
Get:3 http://mx.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libjbig-dev amd64 2.1-3.1ubuntu0.22.04.1 [27.4 kB]
Get:4 http://mx.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libtiffxx5 amd64 4.3.0-6ubuntu0.4 [5 734 B]
Get:5 http://mx.archive.ubuntu.com/ubuntu jammy-updates/main amd64 libtiff-dev amd64 4.3.0-6ubuntu0.4 [314 kB]
Get:6 http://mx.archive.ubuntu.com/ubuntu jammy/universe amd64 libproj-dev amd64 8.2.1-1 [1 594 kB]
Fetched 2 846 kB in 4s (653 kB/s)        
Selecting previously unselected package libdeflate-dev:amd64.
(Reading database ... 302356 files and directories currently installed.)
Preparing to unpack .../0-libdeflate-dev_1.10-2_amd64.deb ...
Unpacking libdeflate-dev:amd64 (1.10-2) ...
Selecting previously unselected package libsqlite3-dev:amd64.
Preparing to unpack .../1-libsqlite3-dev_3.37.2-2ubuntu0.1_amd64.deb ...
Unpacking libsqlite3-dev:amd64 (3.37.2-2ubuntu0.1) ...
Selecting previously unselected package libjbig-dev:amd64.
Preparing to unpack .../2-libjbig-dev_2.1-3.1ubuntu0.22.04.1_amd64.deb ...
Unpacking libjbig-dev:amd64 (2.1-3.1ubuntu0.22.04.1) ...
Selecting previously unselected package libtiffxx5:amd64.
Preparing to unpack .../3-libtiffxx5_4.3.0-6ubuntu0.4_amd64.deb ...
Unpacking libtiffxx5:amd64 (4.3.0-6ubuntu0.4) ...
Selecting previously unselected package libtiff-dev:amd64.
Preparing to unpack .../4-libtiff-dev_4.3.0-6ubuntu0.4_amd64.deb ...
Unpacking libtiff-dev:amd64 (4.3.0-6ubuntu0.4) ...
Selecting previously unselected package libproj-dev:amd64.
Preparing to unpack .../5-libproj-dev_8.2.1-1_amd64.deb ...
Unpacking libproj-dev:amd64 (8.2.1-1) ...
Setting up libjbig-dev:amd64 (2.1-3.1ubuntu0.22.04.1) ...
Setting up libsqlite3-dev:amd64 (3.37.2-2ubuntu0.1) ...
Setting up libdeflate-dev:amd64 (1.10-2) ...
Setting up libtiffxx5:amd64 (4.3.0-6ubuntu0.4) ...
Setting up libtiff-dev:amd64 (4.3.0-6ubuntu0.4) ...
Setting up libproj-dev:amd64 (8.2.1-1) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
gerardo@Tesis:~/Downloads/climpact-master$ sudo apt-get update
Hit:1 http://mx.archive.ubuntu.com/ubuntu jammy InRelease
Hit:2 http://mx.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:3 http://mx.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:4 http://security.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists... Done
gerardo@Tesis:~/Downloads/climpact-master$ sudo apt-get install libudunits2-dev
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed
  libudunits2-dev
0 to upgrade, 1 to newly install, 0 to remove and 131 not to upgrade.
Need to get 364 kB of archives.
After this operation, 767 kB of additional disk space will be used.
Get:1 http://mx.archive.ubuntu.com/ubuntu jammy/universe amd64 libudunits2-dev amd64 2.2.28-3 [364 kB]
Fetched 364 kB in 1s (278 kB/s)          
Selecting previously unselected package libudunits2-dev.
(Reading database ... 302467 files and directories currently installed.)
Preparing to unpack .../libudunits2-dev_2.2.28-3_amd64.deb ...
Unpacking libudunits2-dev (2.2.28-3) ...
Setting up libudunits2-dev (2.2.28-3) ...
Processing triggers for install-info (6.8-4build1) ...
gerardo@Tesis:~/Downloads/climpact-master$ R

R version 4.1.2 (2021-11-01) -- "Bird Hippie"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(shiny) 
runApp()

Attaching package: ‘zoo’

The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric

Loading required package: Kendall
Loading required package: tcltk

Attaching package: ‘tcltk2’

The following object is masked from ‘package:shiny’:

    tag

Need shinyjs help? You can ask any Shiny-related question in the RStudio Community forums:
	https://community.rstudio.com/c/shiny

Attaching package: ‘shinyjs’

The following object is masked from ‘package:tcltk2’:

    disabled

The following object is masked from ‘package:shiny’:

    runExample

The following objects are masked from ‘package:methods’:

    removeClass, show


Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

corrplot 0.92 loaded

Attaching package: ‘shinydashboard’

The following object is masked from ‘package:graphics’:

    box


Attaching package: ‘shinyWidgets’

The following object is masked from ‘package:shinyjs’:

    alert

Error in library(qpdf) : there is no package called ‘qpdf’
What could I do now? Is there any way to fix this? Should I be installing Climpact again? Thanks again Nick for helping me out, you are being such a great help.

Gerardo.

**Comment by GerardoTheMeteorologist** [comment]
HI @heroldn Thanks!!! Now I can open climpact! I just installed it again after doing what you told me and now I can open it. You have saved my life. I really appreciate your help. Have a great day sir. 

Gerardo.
