### ISSUE TITLE
Getting the unused argument error while running climpact Rscript

### ISSUE THREAD

**Issue by farh-an** [ARCCSS-extremes/climpact#106]
Hello everyone,

I was trying to run the sample file of climpact for the historical and I got the error

error in create.indices.from.files(infiles, outdir, file.template, author.data, : unused arguments (root.dir = root.dir, ehfdef = EHF_DEF, wsdin_n = 5, csdin_n = 5, hddheatn_n = 18, cddcoldn_n = 18, gddgrown_n = 10, rxnday_n = 7, rnnmm_n = 30, ntxntn_n = 3, ntxbntnb_n = 3, project.lat2d.coords = TRUE) 
Execution halted

Could you please help me with how to solve this? Thanks in advance.

**Comment by farh-an** [comment]
Hi @heroldn,

I was trying to run the sample file of climpact for the historical and I got the error

error in create.indices.from.files(infiles, outdir, file.template, author.data, : unused arguments (root.dir = root.dir, ehfdef = EHF_DEF, wsdin_n = 5, csdin_n = 5, hddheatn_n = 18, cddcoldn_n = 18, gddgrown_n = 10, rxnday_n = 7, rnnmm_n = 30, ntxntn_n = 3, ntxbntnb_n = 3, project.lat2d.coords = TRUE)
Execution halted

Please guide, thanks

Best,
Farhan

**Comment by heroldn** [comment]
Hi, please let me know what command you're running, what version of R, and if it's the latest Climpact version.

**Comment by farh-an** [comment]
Hi @heroldn 
Rscript climpact.ncdf.wrapper.r
R version 4.1.3 (2022-03-10)
https://github.com/ARCCSS-extremes/climpact
See the attached image below:
![image](https://github.com/ARCCSS-extremes/climpact/assets/74012816/ab144c87-ebb1-4358-bd44-78f3d57d02be)
Note: I am running this in Anaconda CMD.exe Prompt

**Comment by heroldn** [comment]
Ah right, gridded calculations are only supported on Linux https://github.com/ARCCSS-extremes/climpact.

**Comment by farh-an** [comment]
I also checked the installed packages and all of them were installed. See this image;
![image](https://github.com/ARCCSS-extremes/climpact/assets/74012816/16743dfb-68bd-4287-9e28-ac60cf3b153d)

**Comment by farh-an** [comment]
Hi @heroldn, I know it works on Linux and I am running it on a Linux based system. I install ubuntu on the window subsystem for Linux

**Comment by heroldn** [comment]
Right, hmmm. You don't seem to have climdex.pcic.ncdf installed. Not sure why since the script seems to run fine for you. From the climpact root directory, in R, can you run `install.packages("./server/pcic_packages/climdex.pcic.ncdf.climpact.tar.gz",repos=NULL,type="source")`

Then try again.

**Comment by farh-an** [comment]
Hi @heroldn,
The climdex.pcic.netcdf package is already installed but i still re-installed using the command you provided; see below image;
![image](https://github.com/ARCCSS-extremes/climpact/assets/74012816/785ceeed-77ce-4d4d-a9a9-179c027ab5c0)

**Comment by farh-an** [comment]
After installing this i again run the command and got this error message;
![image](https://github.com/ARCCSS-extremes/climpact/assets/74012816/5fca7e5d-e751-4cdb-842d-aac319c73aaa)

**Comment by farh-an** [comment]
I try to install this library but it says that a version of this package might be somewhere else;
![image](https://github.com/ARCCSS-extremes/climpact/assets/74012816/f200f5d0-27be-4a1a-81f1-fcb8d0d994f7)

**Comment by heroldn** [comment]
Brilliant, yes that lmofit issue is in an upcoming merge. You've got a typo in your command, remove the bracket and should install.

**Comment by farh-an** [comment]
I remove the bracket and reinstall the lmofit library is installed but it gives me two warnings;
Warning messages:
1: In install.packages("units") :
  installation of package 'units' had non-zero exit status
2: In install.packages("sf") :
  installation of package 'sf' had non-zero exit status
![image](https://github.com/ARCCSS-extremes/climpact/assets/74012816/63c2b056-262d-4ce0-9cc4-2b0146e872b6)

**Comment by farh-an** [comment]
Can you guide me on how to install or manually compile these two ("units" and "sf") dependencies?

**Comment by heroldn** [comment]
try 'yes' and if that doesn't work then 'no'.

**Comment by farh-an** [comment]
I try yes bit it did not work afterwards i type no it works well but when i again run the script i am getting an error message about spei calculation about its frequency which is 12 and about missing data values = NA

**Comment by farh-an** [comment]
How can I define in the Rscript that I do not want to calculate the spi and spei indices?

**Comment by farh-an** [comment]
Hi, @heroldn are these below calculation message are warnings or just part of indices calculations? see below image
![image](https://github.com/ARCCSS-extremes/climpact/assets/74012816/b104cac7-ef98-4c7e-b720-6f95b567c627)

**Comment by farh-an** [comment]
The lines in the above image are continuous and appear like a loop. I do not understand whether are these warnings or just normal calculation processes. Please guide me, Thanks

**Comment by farh-an** [comment]
The program just finished indices calculations with those lines shown in the above image. It cmd line looks like this;
![image](https://github.com/ARCCSS-extremes/climpact/assets/74012816/0892ecca-78a5-48d5-aad5-5848c03813a8)

**Comment by heroldn** [comment]
Those messages look harmless but are new, probably the latest update to the SPEI package caused it. I'll have to look into silencing them.

**Comment by farh-an** [comment]
Hi @heroldn thank you for the guidance and quick support. I am closing this issue now. Thank you
