### ISSUE TITLE
Add "simple compound indices" to climpact

### ISSUE THREAD

**Issue by jmccomb** [ARCCSS-extremes/climpact#12]
Add "simple compound indices" to climpact (e.g. warm and dry days, wet days followed by warm days, etc.). For Lisa and ET-SCI to provide comment/guidance.

**Comment by lisavalexander** [comment]
I've contacted ET-SCI for some guidance on this. It will require some thought as we didn't talk about an index specifically. We can move this down the priority list in the meantime.
