### ISSUE TITLE
Disconnection from server while running batch process

### ISSUE THREAD

**Issue by Chris-Rankin90** [ARCCSS-extremes/climpact#122]
While running batch process through the online platform I keep getting disconnected from the server. This happens even when trying to run previous files that successfully run. Is anyone else experiencing similar problems?

**Comment by heroldn** [comment]
Hi Chris, do you mean you've successfully run the batch process on these files previously, but now they are failing? This suggests a server issue. If these are different files you're trying to put through batch, are you able to send privately the station data and metadata file you're using?

**Comment by Chris-Rankin90** [comment]
Hello Nicholas,

I tried on new files originally which didn’t work and then tried with files which had previously successfully run as I wanted to make sure I hadn’t made a mistake with the Metadata file or station files. None of these worked yesterday, which lead me to believe it is a server or internet issue.

Kind regards,

Chris Rankin
CSIR
PhD Studentship

**Comment by Chris-Rankin90** [comment]
Hi Nicholas,

I tried emailing the files but it bounces back stating the files are too large for the server.

Kind regards,

Chris Rankin
CSIR
PhD Studentship

**Comment by heroldn** [comment]
You can try upload it to e.g. google drive or similar and send a link. How many stations are there? I'm surprised there were too many to send by email.

**Comment by Chris-Rankin90** [comment]
Hi Nicholas,

I’m not sure either as they are not very large files. And there are 15 files.

Please see below WeTransfer link
https://we.tl/t-EwbfpuxmnD

Kind regards,

Chris Rankin
CSIR
PhD Studentship

**Comment by heroldn** [comment]
Hi sorry haven't had time to look into this. But a possible theory to test (that I hope is wrong). Does the time out happen roughly about 15 minutes into the calculation? If so, can you divide your station list into two or more parts and see if they will run separately. It could be that the server is considering the lack of clicks as inactivity and timing out after 15 min, even though it's still busily calculating the indices.


----------

**Comment by Chris-Rankin90** [comment]
Hi Nicholas,

Thanks for your response.

Unfortunately the server drop happens within about 5 minutes. I did try smaller batches of files and it still dropped.

Kind regards,

Chris Rankin
CSIR
PhD Studentship

**Comment by heroldn** [comment]
Closing this as I think the recent boost in server size has resolved this issue. Open it again if it returns.
