### ISSUE TITLE
Error in paste(tmp.index.name, metadata$year.start, metadata$year.end, : object 'out' not found

### ISSUE THREAD

**Issue by Wendso** [ARCCSS-extremes/climpact#2]
Hello
When running the Rscript for numeros stations, what can be the cause of these errors?
Error in paste(tmp.index.name, metadata$year.start, metadata$year.end, : object 'out' not found
No data to plot

**Comment by heroldn** [comment]
Hi Wendso, I need a little more info. Can you tell me how you're running this and perhaps attach your data.

**Comment by jmccomb** [comment]
The code that caused this error is no longer in Climpact and after recent code changes the behaviour is likely quite different.
So, I'm closing this now but if a similar or any other issue occurs again please raise it by creating a new Github issue.

**Comment by jmccomb** [comment]
Reopening as updated code not merged to master branch yet. I'll update and close this issue when merge is done.
