### ISSUE TITLE
Calculation of linear trends and confidence interval

### ISSUE THREAD

**Issue by jmccomb** [ARCCSS-extremes/climpact#4]
Confirm that Sens slope is used to calculate the linear trends in the output plots and that Mann Kendall is used to calculate confidence interval. We did at least Sens slope for the web version of climpact, start by searching “zsen” in climpact.GUI-functions.r.

**Comment by lisavalexander** [comment]
Check on web version that zsen is being used on plots to draw lines and make inferences about confidence
