### ISSUE TITLE
Add user-specified base period to csv output

### ISSUE THREAD

**Issue by jmccomb** [ARCCSS-extremes/climpact#6]
Add the user-specified base period to the .csv files created for station output (base period is already included in netCDF files).

**Comment by lisavalexander** [comment]
The base period used either has to be in the filename (e.g. 1961-90) or it has to be included in a header in the csv file perhaps. If it was in the filename it would lead to fewer problems with combining different base periods going forward but it would add some backwards compatible issues for those people who are already using the old filenames. Nick should also comment on this one.
