### ISSUE TITLE
Install filed and symbol bugs

### ISSUE THREAD

**Issue by silverbullet1472** [ARCCSS-extremes/climpact#63]
**thanks for the work!**
but I noticed some bug:
**1.**the install command in userguide is wrong('source('installers/climpact.master.installer.r').'  But there is no installers)
**2.**the copyright symbol in ui/ui.r will cause some invalid symbol problem(I am opening with UTF-8, maybe because my laptop system setting is China?)
**3.**cannot runApp successfully
> runApp()

Listening on http://127.0.0.1:4049
Warning: Error in library: there is no package called ‘climdex.pcic.ncdf’
  56: <Anonymous>
Error in library(climdex.pcic.ncdf) : 
  there is no package called ‘climdex.pcic.ncdf’

**Comment by silverbullet1472** [comment]
Hello！
Thanks for your work on new version again! As mentioned above there is some bug, but I could still use it to batch process.
A little question:  Is heat wave excluded when calculating trends? I noticed that in indices folder there are heatwave-related files but no record in trends file.

**Comment by heroldn** [comment]
Hi

I've updated the user guide and removed that symbol.

Thanks for the feedback.

Nick.

**Comment by heroldn** [comment]
Thanks for this too. I've added it to the TO-DO list.

**Comment by heroldn** [comment]
RE your runApp() error, did you manage to run the climpact.master.installer.r script successfully?

**Comment by silverbullet1472** [comment]
> RE your runApp() error, did you manage to run the climpact.master.installer.r script successfully?
Hello!
Yes, alought the path was wrong, I found the installer script and run it.
Maybe there was some error during the installation, but since I only used batch script so I did not work on that afterwards.

**Comment by silverbullet1472** [comment]
![RunAppError](https://user-images.githubusercontent.com/33367899/106845656-5c2e9500-66e6-11eb-9e6c-0bf69610087e.png)
![InstallError](https://user-images.githubusercontent.com/33367899/106845658-5df85880-66e6-11eb-9fcf-87889878c585.png)

Hi,
I redownload the code from github yesterday(2021/2/3), and this is the error information when I use installer script and runapp() function. Hope it;s helpful.

**Comment by heroldn** [comment]
I've adjusted the installer script so it should only install the netcdf package that was causing the original error here if it detects it is on a *nix system. I've also removed the erroneous reference to Runit which isn't needed.
