### ISSUE TITLE
P-Value

### ISSUE THREAD

**Issue by cyndyfem** [ARCCSS-extremes/climpact#77]
Thanks for this wonderful programme.
I am just a bit curious.
I have run the batch script for many stations and I have my outputs. For the trend, I just want to know how to determine if the trends calculated are significant or not. For example, in the RCLIMDEX package, there are always P-values to let you know if the trends are significant or not. But for this new update of climpact, it does not have it. Please, how do I determine the significant trend and insignificant trend?
Thank you.

**Comment by heroldn** [comment]
Hi, the trends in climpact now use Sens slope (not ordinary least squares regression) and the 95% confidence levels are shown on each plot. Thus the lower bound and upper bound show the range of trends to be expected 95% of the time.
