### ISSUE TITLE
Error running climpact.ncdf.wrapper

### ISSUE THREAD

**Issue by martaddi** [ARCCSS-extremes/climpact#78]
I modified the climpact.ncdf.wrapper to run my data but run into the following error. I need help to fix this. I have attached both header of netcdf and climpact script for your kind attention.
Thanks.

[climpact_ncdf.txt](https://github.com/ARCCSS-extremes/climpact/files/6458638/climpact_ncdf.txt)
[netcdf_header.txt](https://github.com/ARCCSS-extremes/climpact/files/6458651/netcdf_header.txt)

Loading required package: PCICt
Loading required package: methods
Error in if (cdx.meta$var.name[i] == "rxdday") { :
  missing value where TRUE/FALSE needed
Calls: create.indices.from.files
Execution halted

**Comment by heroldn** [comment]
Hi, it's probably an issue with your file, are you able to upload it, or a few years from it?

**Comment by martaddi** [comment]
Thank you. I have resolved the challenge. Thanks a lot. 

Sent from Yahoo Mail on Android 
 
  On Sat, May 29, 2021 at 1:31 AM, Nicholas ***@***.***> wrote:   


Hi, it's probably an issue with your file, are you able to upload it, or a few years from it?
