### ISSUE TITLE
Error in data.list$tmin[ind, x] : subscript out of bounds

### ISSUE THREAD

**Issue by JinZarrin** [ARCCSS-extremes/climpact#83]
Dear developer, 
when I use my data to calculate the thresholds, it shows the error like the title, can you please help me out?
[processed_daymet_v4_daily_na_prcp_1981.nc.zip](https://github.com/ARCCSS-extremes/climpact/files/6603689/processed_daymet_v4_daily_na_prcp_1981.nc.zip)

**Comment by heroldn** [comment]
There's an issue where the thresholds script, I believe, needs all 3 variables. So the simple way around this is to just copy some dummy data (like your precip variable) to another variable called "tasdummy" and point the thresholds wrapper script at that for tasmin and tasmax. i.e. **vars=c(prec="prcp",tmax="tasdummy", tmin="tasdummy")**

Obviously ignore thresholds related to temperature in the output netcdf file.

Here's a little workflow to make a dummy temperature variable and copy it back into your file:
ncks -v prcp processed_daymet_v4_daily_na_prcp_1981.nc tmpa.nc
ncrename -v prcp,tasdummy tmpa.nc
ncatted -O -a units,tasdummy,o,c,"degrees_C" tmpa.nc
ncks -A -v tasdummy tmpa.nc processed_daymet_v4_daily_na_prcp_1981.nc

Also your units aren't right, they should be "kg m-2 d-1".

**Comment by JinZarrin** [comment]
Dear Nicholas, I have followed all the steps as you said, but the error is still excited. My file is a little bit, I have already shared it with you by google drive, can you please kindly help me to solve this problem?
![Screen Shot 2021-06-07 at 5 57 56 PM](https://user-images.githubusercontent.com/81920359/121101860-e7658780-c7b9-11eb-8c16-67557a19a99b.png)

**Comment by JinZarrin** [comment]
> There's an issue where the thresholds script, I believe, needs all 3 variables. So the simple way around this is to just copy some dummy data (like your precip variable) to another variable called "tasdummy" and point the thresholds wrapper script at that for tasmin and tasmax. i.e. **vars=c(prec="prcp",tmax="tasdummy", tmin="tasdummy")**
> 
> Obviously ignore thresholds related to temperature in the output netcdf file.
> 
> Here's a little workflow to make a dummy temperature variable and copy it back into your file:
> ncks -v prcp processed_daymet_v4_daily_na_prcp_1981.nc tmpa.nc
> ncrename -v prcp,tasdummy tmpa.nc
> ncatted -O -a units,tasdummy,o,c,"degrees_C" tmpa.nc
> ncks -A -v tasdummy tmpa.nc processed_daymet_v4_daily_na_prcp_1981.nc
> 
> Also your units aren't right, they should be "kg m-2 d-1".

Dear Nicholas, I have followed all the steps as you said, but the error is still excited. My file is a little bit, I have already shared it with you by google drive, can you please kindly help me to solve this problem?
![121101860-e7658780-c7b9-11eb-8c16-67557a19a99b](https://user-images.githubusercontent.com/81920359/121103183-92774080-c7bc-11eb-8633-ee6954b070c9.png)

**Comment by heroldn** [comment]
That problem didn't occur for the 1981 file. I can reproduce it though, your file has an incorrect calendar. Doing an ncump I can see you have exactly 10950 days for a 30 year period, so your calendar should be a "365_day" calendar, not "standard" which is gregorian. Where did you get this from, not a model? Change the calendar and try again (cdo setcalendar,365_day in.nc out.nc).

**Comment by JinZarrin** [comment]
> That problem didn't occur for the 1981 file. I can reproduce it though, your file has an incorrect calendar. Doing an ncump I can see you have exactly 10950 days for a 30 year period, so your calendar should be a "365_day" calendar, not "standard" which is gregorian. Where did you get this from, not a model? Change the calendar and try again (cdo setcalendar,365_day in.nc out.nc).

Thanks a lot, it works now. I convert their coordinate and combine these one year file to a big file, may lose some import information。
