### ISSUE TITLE
Calculation of thresholds seems to not work with the netcdf example

### ISSUE THREAD

**Issue by bzah** [ARCCSS-extremes/climpact#84]
Hello,
I'm trying to calculate Tx90p based on the _climpact.sampledata.gridded.1991-2010.nc_ sample file.

I followed the [user guide](https://github.com/ARCCSS-extremes/climpact/blob/master/www/user_guide/Climpact_user_guide.md#72-a-typical-use-case-of-the-wrapper-scripts).
I skip step 1 because I'm really only interested in the bootstrapping process.
On step 2, it works fine, the nc file generated seems correct when I open it with Panoply.
However, on step 3 I get the following error 
```
Error in check.quantile.validity(quantiles, present.var.list, days.in.base) : 
  Temperature in-base quantiles must contain 10th and 90th percentiles.
Calls: create.indices.from.files ... compute.climdex.indices -> <Anonymous> -> check.quantile.validity
Execution halted
```

Did I miss something?
Thank you for your help.

- [My thresholds file](https://gist.github.com/bzah/b270955b724c65082fceba344fc55f0d)
- [My processing file](https://gist.github.com/bzah/e631d8d66431d09b8c0755c35f7579f4)

**Comment by heroldn** [comment]
A good error message needs to be written for this. I think the problem is simply that you're pointing to a thresholds file that contains data for the same time period as your "infiles". So in your processing file just set thresholds.files to NULL and it should work. You only need to set thresholds.files if the threshold years you're interested in are outside of the years in your data file(s). Otherwise climpact just calculates them at runtime. But let me know if that isn't the issue.

**Comment by bzah** [comment]
Thanks for your reply.
My goal is actually to compare the results of climpact bootstrapping with the ones from icclim and xclim (python libraries).
I assumed the bootstrapping process is only triggered when thresholds.files is not NULL but I'm not sure about that.

**Comment by heroldn** [comment]
If you mean you want to look at percentiles calculated inside the base period I don't think that's possible with climpact, but I'd have to confirm. But climpact uses the excellent package climdex.pcic for all of these calculations so you might want to look at that directly - and you might find it more practical than having to put everything through climpact, if you just want to test a time series for comparison.

**Comment by bzah** [comment]
I don't really intent to look at the percentiles themself but more at the resulting netcdf.
I wanted to use climpact instead of climdex because my inputs are netcdf files and there is much more documentation on climpact to setup a quick test.
Anyway thanks for your help.

**Comment by heroldn** [comment]
In that case you don't need to use a thresholds file, just run the wrapper script and boot strapping will be used.
