### ISSUE TITLE
Record and output the date when extremes occur

### ISSUE THREAD

**Issue by jmccomb** [ARCCSS-extremes/climpact#9]
Record and output the date when extremes occur. May be tricky in terms of the code but a very important feature to have. E.g. The TXx index records the hottest day-time temperature each year or month, but we want to also have the date that this occurs recorded as well.

**Comment by lisavalexander** [comment]
Add an extra csv file with the date on which hottest, wettest, heatwave occurred and the value of the index. Add 'occurdate' to the end of the filename (or something similar). We can provide list of indices for which this amendment is required.
