### ISSUE TITLE
  Error in FUN(X[[i]], ...) : Temperature in-base quantiles must contain 10th and 90th percentiles.

### ISSUE THREAD

**Issue by user241276** [ARCCSS-extremes/climpact#90]
Hello,

I am running the `climdex.pcic.ncdf` R package and I get the following error:

```
Error in FUN(X[[i]], ...) :
  Temperature in-base quantiles must contain 10th and 90th percentiles.
Calls: create.indices.from.files ... local.filter.func -> write.climdex.results -> lapply -> FUN
Execution halted
```

With my script I am trying to compute indices with CMIP6 model data, using the `create.indices.from.files` function, for the historical period (1950-2014) with thresholds computed on 1981-2000.

But the script works when I compute indices on future CMIP6 data (2015-2100) with the same thresholds computed on 1981-2000.

The `base.range` I am using for both cases is `c(1981,2000)`.

Do you have any suggestion?

Thanks

**Comment by heroldn** [comment]
Can you send or paste your wrapper scripts. It's possibly this error comes about from supplying a thresholds file when you're calculating the indices for the historical period (in which case you wouldn't need to supply a thresholds file). Either way, I'm sure I've seen this before.

**Comment by user241276** [comment]
hello,

thanks. indeed I was using the threshold files for the historical period too. Now it is ok.

best

**Comment by heroldn** [comment]
Good to hear. Something that needs to be handled better.
