### ISSUE TITLE
Temperature in-base quantiles must contain 10th and 90th percentiles. who can help me out, please

### ISSUE THREAD

**Issue by JinZarrin** [ARCCSS-extremes/climpact#94]
Hi there,
I use the Tasmin data (tasmin_day_ACCESS-CM2_historical_r1i1p1f1_19500101-19991231.nc) and the prepared threshold (thresholds_day_ACCESS-CM2_historical_r1i1p1f1_19810101-20101231.nc) to run the indices.r to calculate the extreme temperature indices, base.range is 1981-2010, but when I run it, the errors shows like the following picture, can you please kindly tell me how to solve it
![image](https://user-images.githubusercontent.com/81920359/150019450-712a3a24-3337-4e4b-936a-d3070cf889dd.png)

**Comment by heroldn** [comment]
Off the top of my head this may have to do with an issue where climpact expects all 3 variables for thresholds. Are there only tasmin thresholds in your thresholds file? I'm not 100% sure about this, but the quickest way to check is to do this process with all 3 variables (and if you only have tasmin then just create a tasmax and prec variable copying the tasmin data - so dummy variables - and then ignore any tasmax/prec outputs). It's not elegant but it may be the cause of this message.

**Comment by JinZarrin** [comment]
Hi heroldn, 
Thanks for your kind reply. In fact, I use tasmax tasmin and pr, these three variables. When I worked on the ssp scenarios, base range is 1981-2010, it works. However, when I do calculations on historical scenario, from 1951-2014, it shows the above error, my base range is also 1981-2010. I found another people who come accords the same problem as me. He solved the problem as follow picture, but indeed my base range is 1981-2010, I can’t change it. So it may a bug of this package or I may took something wrong? Can you kindly help me out?
![6776EEEF-04AC-4A33-BAF0-91FBCE454DF5](https://user-images.githubusercontent.com/81920359/150027099-ba5c9b87-3310-46c5-9286-6274e3877c09.png)

**Comment by heroldn** [comment]
If your base period is 1981-2010 and your calculating indices on 1951-2014 then just remove the threshold file from your wrapper script (i.e. don't specify it). That does confuse climpact. The in-base-period thresholds will be calculated at runtime so you don't need to specify a thresholds file.

**Comment by JinZarrin** [comment]
> If your base period is 1981-2010 and your calculating indices on 1951-2014 then just remove the threshold file from your wrapper script (i.e. don't specify it). That does confuse climpact. The in-base-period thresholds will be calculated at runtime so you don't need to specify a thresholds file.

Dear Heroldn, thanks a lot for your kind help, now it works.
